#!/usr/bin/env python

Import('env')

env_microprofile = env.Clone()

# Godot's own source files
#env_bmp.add_source_files(env.modules_sources, "*.cpp")
env_microprofile.add_source_files(env.drivers_sources, "*.cpp")

Export('env')